---
kind: pipeline
type: docker
name: default

steps:
  - name: yml_lint
    image: sdesbure/yamllint:latest
    commands:
      - yamllint .drone.yml
  - name: dockerfile_lint
    image: hadolint/hadolint:v1.19.0
    commands:
      - hadolint Dockerfile
  - name: docker
    image: plugins/docker:19.03
    environment:
      DOCKER_BUILDKIT: 1
    settings:
      username: hsmtkk
      password:
        from_secret: dockerhub_token
      repo: hsmtkk/simple_board
